- name: Create DocRoot folder
  file: path=/var/html state=directory mode=0777

- name: Copy update config file
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf backup=yes
  when: ansible_distribution == "Ubuntu"
  notify:
          - Restart Apache in Ubuntu


- name: Grant Permission to all users for DocRoot in Ubuntu
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf backup=yes
  when: ansible_distribution == "Ubuntu"
  notify:
          - Restart Apache in Ubuntu

- name: Update Config file in CentOS
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  when: ansible_distribution == "CentOS"
  notify:
          - Restart Apache in CentOS
...
