- name: Demonstrates use of docker_container module
  hosts: localhost
  tasks:
          - name: Provision docker container
            docker_container:
                    image: "verizon/ansuble-ubuntu"
                    name: ubuntu{{item}}
                    state: started
                    ports:
                            - "800{{item}}:80"
                            - "200{{item}}:22"
            with_sequence: start=1 end=4


          - name: Provision docker container
            docker_container:
                    image: "verizon/ansible-centos"
                    name: centos{{item}}
                    state: started
                    ports:
                            - "800{{item}}:80"
                            - "200{{item}}:22"
            with_sequence: start=5 end=9
