- name: Demonstrates Install softwares via playboot
  hosts: all
  become: yes
  vars:
          software_tools:
                  - vim
                  - tree

  tasks: 
  - name: Install vim
    apt: name="{{item}}" state=latest update_cache=yes
    with_items: "{{software_tools}}"
# state = absent, present, latest
  
  - name: Check tree utulity
    shell: tree /
    register: output

  - name: Print the tree output
    debug: var=output

